[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38']

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "gitpython",
    "setuptools_rust"
]
build-backend = "setuptools.build_meta"
