[tool.black]
line-length = 100
target-version = ['py37', 'py38', 'py39']
skip-string-normalization = true

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "gitpython",
]
build-backend = "setuptools.build_meta"
